# Generated by Django 4.2.2 on 2023-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('price_sp', models.DecimalField(decimal_places=1, max_digits=10)),
                ('name_arabic', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=1028, null=True)),
            ],
        ),
    ]
