# Generated by Django 4.2.2 on 2023-08-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
